# Generated by Django 5.2.6 on 2026-04-30 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_hardening_fields_and_websocketticket'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otp',
            new_name='users_otp_phone_n_33906b_idx',
            old_name='users_otp_phone_i_4c040f_idx',
        ),
        migrations.RenameIndex(
            model_name='websocketticket',
            new_name='users_webso_ticket_1b5686_idx',
            old_name='users_webso_ticket_4c5442_idx',
        ),
        migrations.RenameIndex(
            model_name='websocketticket',
            new_name='users_webso_user_id_11ab7e_idx',
            old_name='users_webso_user_id_f97041_idx',
        ),
    ]
