# Generated by Django 5.2.6 on 2026-05-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_contact_phone_and_invitelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(blank=True, default='Available', max_length=139),
        ),
    ]
