# Generated by Django 5.2.6 on 2026-05-21 19:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('accepted', 'Accepted'), ('active', 'Active'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('missed', 'Missed'), ('ended', 'Ended'), ('failed', 'Failed'), ('busy', 'Busy')], default='initiated', max_length=20)),
                ('room_name', models.CharField(max_length=255, unique=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_call_sessions', to=settings.AUTH_USER_MODEL)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_call_sessions', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_call_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['caller'], name='calls_calls_caller__4ff76e_idx'), models.Index(fields=['receiver'], name='calls_calls_receive_583dd8_idx'), models.Index(fields=['status'], name='calls_calls_status_7d79e0_idx'), models.Index(fields=['created_at'], name='calls_calls_created_6c8bf7_idx'), models.Index(fields=['room_name'], name='calls_calls_room_na_88b52d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('caller', models.F('receiver')), _negated=True), name='calls_session_caller_receiver_different')],
            },
        ),
    ]
