# Generated by Django 5.2.6 on 2026-06-19 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='chime_external_meeting_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='chime_media_region',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='chime_meeting_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='chime_meeting_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='provider',
            field=models.CharField(default='livekit', max_length=20),
        ),
        migrations.AddField(
            model_name='callsession',
            name='provider_error_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='CallAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chime_attendee_id', models.CharField(max_length=128)),
                ('chime_external_user_id', models.CharField(max_length=128)),
                ('chime_join_token', models.TextField()),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='calls.callsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_attendees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('call', 'user'), name='calls_attendee_unique_per_call_user')],
            },
        ),
    ]
