# Generated by Django 5.2.6 on 2026-06-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_callsession_chime_external_meeting_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsession',
            name='provider',
            field=models.CharField(default='chime', max_length=20),
        ),
    ]
