# Generated by Django 6.0.3 on 2026-03-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
