# Generated by Django 5.2.6 on 2026-04-30 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_hardening_and_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chat',
            new_name='chat_chat_last_ac_2aa3f0_idx',
            old_name='chat_chat_last_ac_164ad4_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_chat_id_0c7b25_idx',
            old_name='chat_messag_chat_id_28616d_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_sender__b02346_idx',
            old_name='chat_messag_sender__5a7cfe_idx',
        ),
        migrations.RenameIndex(
            model_name='messagestatus',
            new_name='chat_messag_user_id_03f6f7_idx',
            old_name='chat_messag_user_id_4cb2e0_idx',
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
