# Generated by Django 5.2.6 on 2026-05-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_lifecycle_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='deleted_at_user1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='deleted_at_user2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='deleted_for_user1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='deleted_for_user2',
            field=models.BooleanField(default=False),
        ),
    ]
