# Generated by Django 5.2.6 on 2026-05-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chat_deleted_at_user1_chat_deleted_at_user2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_forwarded',
            field=models.BooleanField(default=False),
        ),
    ]
