# Generated by Django 5.2.6 on 2026-05-18 14:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='statuses/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='status_thumbs/')),
                ('background_color', models.CharField(default='#128C7E', max_length=20)),
                ('font_size', models.IntegerField(default=28)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('privacy', models.CharField(choices=[('all_contacts', 'All Contacts'), ('except', 'All Except'), ('only', 'Only Share With')], default='all_contacts', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_statuses', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='status.userstatus')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusPrivacyException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_type', models.CharField(choices=[('except', 'Hide from this user'), ('only', 'Show only to this user')], max_length=10)),
                ('excepted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepted_from', to=settings.AUTH_USER_MODEL)),
                ('status_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('status_owner', 'excepted_user')},
            },
        ),
        migrations.AddIndex(
            model_name='userstatus',
            index=models.Index(fields=['user', 'is_active', 'expires_at'], name='status_user_user_id_f14ec6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='statusview',
            unique_together={('status', 'viewer')},
        ),
    ]
